### ISSUE TITLE
Importing Discogs collection exports

### ISSUE THREAD

**Issue by psychotrees** [AyeTSG/Kulector#5]
I think it would be interesting if the UI could import Discogs exports of collections into a Kulection.

**Comment by AyeTSG** [comment]
I might consider this, I haven't needed to export from Discogs before... what format is their data exported in?

**Comment by AyeTSG** [comment]
I'll take a look on an export of my own. If it's just CSV, I don't think it'll be able to import cover images into the item image unfortunately.

**Comment by AyeTSG** [comment]
Yeah, it doesn't look like item images will be possible here, but I'll definitively consider taking a crack at Discogs collection import!

**Comment by AyeTSG** [comment]
Ah, you're right, then yeah it would be a bit more work there, but it should be possible.

**Comment by AyeTSG** [comment]
Implemented in #8
