### ISSUE TITLE
File/folder association

### ISSUE THREAD

**Issue by psychotrees** [AyeTSG/Kulector#7]
Each item could be associated with a file or folder, and opened in the appropriate app.
Examples:
- Music-related items (records, CDs) could be associated with a folder containing the ripped/downloaded tracks and opened in a preferred music player.
- Games could be associated with a ROM and opened in an emulator.
- Books could be associated with an e-book file (EPUB, PDF, etc.) and opened in a reader.
- And so on.

**Comment by AyeTSG** [comment]
That's a bit too much for what I intended this app for. I intended it to be used to catalog **physically existing** items, such as rocks, bugs, or other stuff you'd go out and collect. I don't feel it fits the primary purpose.
